#!/usr/bin/env python3
"""
Build a Figure 1C pathway summary table.

The output contains:
- the pathways shown in Figure 1C;
- pathway/cluster information;
- statistical evidence from the selected-pathway results;
- all genes annotated to each pathway;
- qualifying DNV-carrying genes in each pathway;
- separate LoF and Dmis gene/variant columns.

Run from the repository root:
    python scripts/build_figure1c_pathway_table.py
"""

from __future__ import annotations

import os
import re

import numpy as np
import pandas as pd


# ==========================================================
# Files
# ==========================================================

# Generated by the updated Figure 1C network script.
NETWORK_NODE_FILE = "results/pathway_network_nodes.tsv"

# Contains the main LoF, Dmis, and LoF+Dmis pathway statistics.
SELECTED_PATHWAY_FILE = (
    "results/significant_pathway_union_lof_vs_dmis.tsv"
)

# Contains the complete GO gene set for each pathway.
COMMON_PATHWAY_FILE = "results/common_pathway_universe.tsv"

# Annotated case DNVs.
CASE_FILE = "results/EA_TEF_cases_annotated.tsv"

BLACKLIST_FILE = "data/09GENCODEV19_blacklist.txt"

OUTPUT_FILE = "results/Figure1C_pathway_statistics_and_DNV_genes.tsv"


# ==========================================================
# Parameters
# ==========================================================

CASE_GENE_COLUMN = "HGNC"
SAMPLE_COLUMN = "Sample_id"
VARIANT_TYPE_COLUMN = "Var_type"
PHENOTYPE_COLUMN = "Syndormic or not"

SCORE_COLUMN = "MisFit_S"
MISFIT_THRESHOLD = 0.005

LOF_VARIANT_TYPES = {
    "lof",
    "frameshift",
    "stop_gained",
    "splice_acceptor",
    "splice_donor",
    "start_lost",
}

MISSENSE_VARIANT_TYPES = {
    "mis",
    "missense",
}


# ==========================================================
# Helpers
# ==========================================================

def parse_gene_set(value: object) -> set[str]:
    if pd.isna(value):
        return set()

    return {
        gene.strip().upper()
        for gene in str(value).split(";")
        if gene.strip()
    }


def join_genes(genes: set[str] | list[str]) -> str:
    return ";".join(sorted(set(genes)))


def load_blacklisted_genes(path: str) -> set[str]:
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Blacklist file was not found: {path}"
        )

    genes: set[str] = set()

    with open(
        path,
        "r",
        encoding="utf-8",
        errors="replace",
    ) as handle:
        for raw_line in handle:
            line = raw_line.strip()

            if not line or line.startswith("#"):
                continue

            gene = re.split(
                r"[\t, ]+",
                line,
                maxsplit=1,
            )[0].strip()

            if gene:
                genes.add(gene.upper())

    if not genes:
        raise ValueError(
            f"No genes were loaded from {path}"
        )

    return genes


def require_columns(
    dataframe: pd.DataFrame,
    required: set[str],
    file_path: str,
) -> None:
    missing = required - set(dataframe.columns)

    if missing:
        raise ValueError(
            f"Missing required columns in {file_path}: "
            f"{sorted(missing)}"
        )


# ==========================================================
# Load files
# ==========================================================

print("Loading blacklist...")
blacklisted_genes = load_blacklisted_genes(
    BLACKLIST_FILE
)

print(
    f"Blacklisted genes loaded: "
    f"{len(blacklisted_genes)}"
)


print("Loading Figure 1C node table...")
network_nodes = pd.read_csv(
    NETWORK_NODE_FILE,
    sep="\t",
    low_memory=False,
)

require_columns(
    network_nodes,
    {"Pathway"},
    NETWORK_NODE_FILE,
)


print("Loading selected-pathway statistics...")
selected = pd.read_csv(
    SELECTED_PATHWAY_FILE,
    sep="\t",
    low_memory=False,
)

require_columns(
    selected,
    {"Pathway"},
    SELECTED_PATHWAY_FILE,
)


print("Loading complete pathway gene sets...")
common = pd.read_csv(
    COMMON_PATHWAY_FILE,
    sep="\t",
    low_memory=False,
)

require_columns(
    common,
    {
        "Pathway",
        "Genes",
    },
    COMMON_PATHWAY_FILE,
)


print("Loading annotated case DNVs...")
cases = pd.read_csv(
    CASE_FILE,
    sep="\t",
    low_memory=False,
    encoding="latin1",
)

require_columns(
    cases,
    {
        SAMPLE_COLUMN,
        VARIANT_TYPE_COLUMN,
        CASE_GENE_COLUMN,
        SCORE_COLUMN,
        PHENOTYPE_COLUMN,
    },
    CASE_FILE,
)


# ==========================================================
# Standardize pathway names
# ==========================================================

for dataframe in (
    network_nodes,
    selected,
    common,
):
    dataframe["Pathway"] = (
        dataframe["Pathway"]
        .astype(str)
        .str.strip()
    )

if network_nodes["Pathway"].duplicated().any():
    raise ValueError(
        "The Figure 1C node table contains duplicate pathways."
    )

if selected["Pathway"].duplicated().any():
    raise ValueError(
        "The selected-pathway statistics table contains "
        "duplicate pathways."
    )

if common["Pathway"].duplicated().any():
    raise ValueError(
        "The common pathway universe contains duplicate pathways."
    )


# ==========================================================
# Prepare complete pathway gene sets
# ==========================================================

common["All_Pathway_Gene_Set"] = common["Genes"].apply(
    parse_gene_set
)

common["All_Pathway_Gene_Set"] = (
    common["All_Pathway_Gene_Set"]
    .apply(
        lambda genes: genes - blacklisted_genes
    )
)

common["All_Genes_In_Pathway"] = (
    common["All_Pathway_Gene_Set"]
    .apply(join_genes)
)

common["Total_Genes_In_Pathway"] = (
    common["All_Pathway_Gene_Set"]
    .map(len)
)


# ==========================================================
# Prepare qualifying complex-case DNVs
# ==========================================================

cases[SAMPLE_COLUMN] = (
    cases[SAMPLE_COLUMN]
    .astype(str)
    .str.strip()
)

cases[PHENOTYPE_COLUMN] = (
    cases[PHENOTYPE_COLUMN]
    .astype("string")
    .str.strip()
    .str.lower()
)

cases[VARIANT_TYPE_COLUMN] = (
    cases[VARIANT_TYPE_COLUMN]
    .astype(str)
    .str.strip()
    .str.lower()
)

cases[SCORE_COLUMN] = pd.to_numeric(
    cases[SCORE_COLUMN],
    errors="coerce",
)

# MisFit_S = -1 is treated as missing.
cases.loc[
    cases[SCORE_COLUMN] == -1,
    SCORE_COLUMN,
] = np.nan

lof_mask = cases[
    VARIANT_TYPE_COLUMN
].isin(
    LOF_VARIANT_TYPES
)

dmis_mask = (
    cases[
        VARIANT_TYPE_COLUMN
    ].isin(
        MISSENSE_VARIANT_TYPES
    )
    & cases[SCORE_COLUMN].notna()
    & cases[SCORE_COLUMN].ge(
        MISFIT_THRESHOLD
    )
)

cases = cases[
    cases[PHENOTYPE_COLUMN].eq("complex")
    & (lof_mask | dmis_mask)
].copy()

cases = cases.dropna(
    subset=[CASE_GENE_COLUMN]
).copy()

cases[CASE_GENE_COLUMN] = (
    cases[CASE_GENE_COLUMN]
    .astype(str)
    .str.strip()
    .str.upper()
)

cases = cases[
    cases[CASE_GENE_COLUMN].ne("")
    & ~cases[CASE_GENE_COLUMN].isin(
        blacklisted_genes
    )
].copy()

cases["DNV_Class"] = np.where(
    cases[VARIANT_TYPE_COLUMN].isin(
        LOF_VARIANT_TYPES
    ),
    "LoF",
    "Dmis",
)

print(
    "Qualifying complex-case DNV rows: "
    f"{len(cases)}"
)

print(
    "Unique qualifying DNV genes: "
    f"{cases[CASE_GENE_COLUMN].nunique()}"
)


# ==========================================================
# Build one summary row per Figure 1C pathway
# ==========================================================

figure_pathways = set(
    network_nodes["Pathway"]
)

missing_from_common = (
    figure_pathways
    - set(common["Pathway"])
)

if missing_from_common:
    raise ValueError(
        "Figure 1C pathways missing from the common "
        "pathway universe: "
        f"{sorted(missing_from_common)}"
    )

missing_from_statistics = (
    figure_pathways
    - set(selected["Pathway"])
)

if missing_from_statistics:
    raise ValueError(
        "Figure 1C pathways missing from the selected "
        "pathway statistics table: "
        f"{sorted(missing_from_statistics)}"
    )


rows: list[dict[str, object]] = []

common_lookup = common.set_index(
    "Pathway"
)

for pathway in sorted(figure_pathways):
    pathway_gene_set = common_lookup.at[
        pathway,
        "All_Pathway_Gene_Set",
    ]

    pathway_cases = cases[
        cases[CASE_GENE_COLUMN].isin(
            pathway_gene_set
        )
    ].copy()

    lof_cases = pathway_cases[
        pathway_cases["DNV_Class"].eq("LoF")
    ]

    dmis_cases = pathway_cases[
        pathway_cases["DNV_Class"].eq("Dmis")
    ]

    all_dnv_genes = set(
        pathway_cases[CASE_GENE_COLUMN]
    )

    lof_genes = set(
        lof_cases[CASE_GENE_COLUMN]
    )

    dmis_genes = set(
        dmis_cases[CASE_GENE_COLUMN]
    )

    rows.append(
        {
            "Pathway": pathway,
            "Total_Genes_In_Pathway": int(
                common_lookup.at[
                    pathway,
                    "Total_Genes_In_Pathway",
                ]
            ),
            "All_Genes_In_Pathway": (
                common_lookup.at[
                    pathway,
                    "All_Genes_In_Pathway",
                ]
            ),
            "DNV_Observed_Variants": int(
                len(pathway_cases)
            ),
            "DNV_Observed_Genes": int(
                len(all_dnv_genes)
            ),
            "DNV_Genes": join_genes(
                all_dnv_genes
            ),
            "LoF_Observed_Variants": int(
                len(lof_cases)
            ),
            "LoF_Observed_Genes": int(
                len(lof_genes)
            ),
            "LoF_DNV_Genes": join_genes(
                lof_genes
            ),
            "Dmis_Observed_Variants": int(
                len(dmis_cases)
            ),
            "Dmis_Observed_Genes": int(
                len(dmis_genes)
            ),
            "Dmis_DNV_Genes": join_genes(
                dmis_genes
            ),
            "DNV_Samples": ";".join(
                sorted(
                    set(
                        pathway_cases[
                            SAMPLE_COLUMN
                        ]
                    )
                )
            ),
        }
    )

dnv_summary = pd.DataFrame(rows)


# ==========================================================
# Merge cluster information and statistical evidence
# ==========================================================

# Keep all node-table columns because they describe the exact
# pathways and clusters displayed in Figure 1C.
node_columns = list(network_nodes.columns)

# Keep all selected-pathway columns so the output carries the
# complete statistical evidence already used for Table S5.
selected_columns = [
    column
    for column in selected.columns
    if column != "Pathway"
]

output = (
    network_nodes[node_columns]
    .merge(
        selected[
            [
                "Pathway",
                *selected_columns,
            ]
        ],
        on="Pathway",
        how="left",
        validate="one_to_one",
        suffixes=(
            "_Figure1C",
            "_Statistics",
        ),
    )
    .merge(
        dnv_summary,
        on="Pathway",
        how="left",
        validate="one_to_one",
    )
)


# ==========================================================
# Arrange the most useful columns first
# ==========================================================

preferred_front = [
    "Cluster",
    "Ontology_Cluster_Name",
    "Pathway",
    "GO_ID",
    "GO_Term_Name",
    "BestFWER",
    "Minimum_FWER",
    "Significant_In",
    "Driver",
    "DNV_Observed_Variants",
    "DNV_Observed_Genes",
    "DNV_Genes",
    "LoF_Observed_Variants",
    "LoF_Observed_Genes",
    "LoF_DNV_Genes",
    "Dmis_Observed_Variants",
    "Dmis_Observed_Genes",
    "Dmis_DNV_Genes",
    "Total_Genes_In_Pathway",
    "All_Genes_In_Pathway",
    "DNV_Samples",
]

front_columns = [
    column
    for column in preferred_front
    if column in output.columns
]

remaining_columns = [
    column
    for column in output.columns
    if column not in front_columns
]

output = output[
    front_columns
    + remaining_columns
]


# ==========================================================
# Save
# ==========================================================

sort_columns = [
    column
    for column in [
        "Cluster",
        "BestFWER",
        "Minimum_FWER",
        "Pathway",
    ]
    if column in output.columns
]

if sort_columns:
    output = output.sort_values(
        sort_columns,
        na_position="last",
    ).reset_index(drop=True)

output_directory = os.path.dirname(
    OUTPUT_FILE
)

if output_directory:
    os.makedirs(
        output_directory,
        exist_ok=True,
    )

output.to_csv(
    OUTPUT_FILE,
    sep="\t",
    index=False,
)

print()
print(
    output[
        [
            column
            for column in [
                "Cluster",
                "Pathway",
                "DNV_Observed_Variants",
                "LoF_Observed_Variants",
                "Dmis_Observed_Variants",
                "DNV_Genes",
                "BestFWER",
                "Minimum_FWER",
            ]
            if column in output.columns
        ]
    ].to_string(index=False)
)
print()

print(
    f"Figure 1C pathways written: "
    f"{len(output)}"
)

print(
    f"Saved table to: {OUTPUT_FILE}"
)